name: Test Jekyll Build

on:
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  #### TEST THAT THE GH PAGES SITE GETS BUILT WITHOUT ERRORS ####
  test:
    name: "Build GHPages site"
    if: github.repository == 'PHPCSStandards/PHPCSDevTools'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Use the version as per https://pages.github.com/versions/.
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Test building the GH Pages site
        run: bundle exec jekyll build
